services:
  abellot-web:
    image: nginx:latest
    container_name: abellot-web
    volumes:
      - /root/abellot/contenidors/abellot-web/web:/usr/share/nginx/html
    ports:
      - 8083:80
    restart: unless-stopped
